

deep-remove-regex:
- "/grpc-google-.*/src"
- "/proto-google-.*/src"
- "/google-.*/src"
- "/samples/snippets/generated"

deep-preserve-regex:
- "/google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/it"

deep-copy-regex:
- source: "/google/cloud/accessapproval/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-accessapproval-$1/src"
- source: "/google/cloud/accessapproval/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-accessapproval-$1/src"
- source: "/google/cloud/accessapproval/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-accessapproval/src"
- source: "/google/cloud/accessapproval/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/$1/samples/snippets/generated"

api-name: accessapproval
